// ============================================================
// constants.js
// 앱 전역 상수, UI 텍스트 딕셔너리, STT/AI 모델 목록
// ============================================================

const HISTORY_KEY = 'vlive_history';
const CAPTION_SEGMENTS_KEY = 'vlive_caption_segments';
const TRANSLATION_MIN_INTERVAL_MS = 2500;
const MIC_PERMISSION_VALUE = "__request_mic_permission";
const DISPLAY_TRANSCRIPT_LIMIT = 3000;
const HISTORY_SAVE_INTERVAL_MS = 15000;
const LOCAL_WHISPER_MODEL = "Xenova/whisper-tiny";
const FALLBACK_WHISPER_MODEL = "Xenova/whisper-base";
const LOCAL_MIN_RMS = 0.003;
const CAPTURE_TIMING = { localRecordMs: 2000, cloudRecordMs: 3500, restartDelayMs: 300 };
const PLAN_KEY = 'vlive_plan';
const USAGE_KEY = 'vlive_usage_daily';
const LESSON_META_KEY = 'vlive_lesson_meta';
const UI_LANGUAGE_KEY = 'vlive_ui_language';

// ── 전역 상태 변수 (추가) ──────────────────────────────────
let transcriptText = "";
let captionSegments = [];
let sessionCaptionStartedAt = 0;

const FREE_LIMITS = {
    cloudSeconds: 10 * 60,
    aiRequests: 3,
    finalTranscribes: 1,
    historyItems: 10
};
const PREMIUM_LIMITS = {
    cloudSeconds: 600 * 60,
    aiRequests: 300,
    finalTranscribes: 60,
    historyItems: 100
};

const UI_TEXT = {
    en: {
        navLive: "Live captions",
        navHistory: "History",
        navGuide: "Guide",
        statusReady: "Ready",
        micLevel: "Mic level",
        myPage: "My page",
        login: "Log in",
        heroTitle: "Live lecture captions",
        heroBody: "Share captions on screen and by link during class, then create lecture notes, SRT/VTT, and PDF after the session.",
        micLabel: "Available microphone",
        micSelect: "Select an available microphone",
        micPermission: "Allow microphone permission",
        modeLabel: "Caption mode",
        localMode: "Process on this device",
        cloudMode: "High-accuracy cloud",
        settings: "Settings",
        translationLabel: "Translation language",
        noTranslation: "No translation",
        lessonTitle: "Class title",
        lessonPlaceholder: "e.g. Grade 9 Science Unit 2",
        lessonNote: "The class title is saved with history. Speaker separation or institution-owned API keys are available in advanced settings.",
        premiumExperiment: "Lecture Premium preview",
        premiumPreview: "View Lecture Premium",
        freePreview: "View Free",
        flowLiveTitle: "Live captions",
        flowLiveBody: "Show microphone audio as large captions in real time.",
        flowShareTitle: "Student link sharing",
        flowShareBody: "Send captions to student screens with a QR link.",
        flowNotesTitle: "Class materials",
        flowNotesBody: "Turn captions into lecture notes, SRT/VTT, and PDF.",
        sampleTitle: "Sample output",
        sampleBody: "After class, organize the transcript into review-ready material.",
        sampleApply: "Load sample",
        lectureNote: "Lecture note",
        sampleLessonTitle: "Grade 9 Science: Current and Voltage",
        sampleLessonBody: "Organize key concepts, confusing terms, review questions, and next-class tasks into one document.",
        subtitleFile: "Caption file",
        subtitleFileBody: "Create timestamped caption files ready for recorded lecture uploads.",
        cloudHigh: "High-accuracy cloud",
        serverCredit: "Using LiveNote server credits · No API key setup needed",
        advancedSettings: "Advanced settings",
        closeSettings: "Close settings",
        advancedApi: "Advanced API settings",
        useMyApi: "Use my API key",
        provider: "Provider",
        model: "Model",
        apiKey: "API key",
        keyStorage: "Key storage",
        saveBrowser: "Save in this browser",
        saveSession: "Save for this session only",
        extraSettings: "Extra settings",
        extraPlaceholder: "Service URL or region",
        diarization: "Use speaker separation",
        providerHelp: "Free/Premium can use LiveNote server credits immediately. Only developers or institutions need their own API key.",
        apiCostNote: "If you use your own API key, provider costs may apply instead of LiveNote usage limits. Keys are saved only in this browser.",
        groqKeyTest: "Enter Groq key for testing",
        makeGroqKey: "Create Groq API key",
        makeOpenAiKey: "Create OpenAI API key",
        joinGladia: "Join Gladia",
        joinSpeechmatics: "Join Speechmatics",
        fontSize: "Font size",
        textColor: "Text color",
        captionBackground: "Caption background",
        opacity: "Opacity",
        settingsNote: "Changes apply immediately to live captions, shared view, and PIP mode, and are saved in this browser.",
        livePanel: "Live captions",
        reset: "Reset",
        largeCaption: "Large caption",
        defaultView: "Default view",
        pipMode: "PIP mode",
        classMaterials: "Class materials",
        materialSettings: "Material settings",
        advancedAiApi: "Advanced class-material API settings",
        aiEmpty: "After class, create key summaries, review points, and assignment hints.",
        questionPlaceholder: "Ask a question about the captions",
        send: "Send",
        meetingMinutes: "Meeting minutes",
        lectureNotes: "Lecture notes",
        consultingRecord: "Consulting record",
        createMaterials: "Create materials",
        copyMarkdown: "Copy Markdown",
        downloadMd: "Download MD",
        startCaptions: "Start captions",
        endSession: "End session",
        summarize: "Summarize",
        downloadTxt: "Download TXT",
        downloadRecording: "Download recording",
        finalTranscribe: "Final transcribe",
        shareStudentLink: "Share student link",
        debugReady: "System ready.",
        sharedBeta: "Shared view beta",
        backToLive: "Back to live captions",
        roomId: "Room ID",
        roomPlaceholder: "Enter or generate a room ID",
        generateId: "Generate ID",
        currentStatus: "Current status",
        waiting: "Waiting to connect...",
        role: "Role",
        senderRole: "Send captions (phone)",
        receiverRole: "Receive captions (PC/tablet)",
        sharePlaceholder: "Create a room ID to generate a share link.",
        copyLink: "Copy link",
        stageLink: "Stage link",
        makeQr: "Create QR",
        audienceNote: "Audience members can join receiver mode by link or QR. Stage mode is for projectors and large screens.",
        sharedView: "Shared view",
        stageMode: "Stage mode",
        stageEnd: "Exit stage",
        clearScreen: "Clear screen",
        connect: "Connect",
        disconnect: "Disconnect",
        savedHistory: "Saved caption history",
        deleteAll: "Delete all",
        privacy: "Privacy Policy",
        terms: "Terms",
        contact: "Contact",
        authTitle: "Premium login",
        authNote: "Log in first to connect Premium features to your account.",
        close: "Close",
        googleContinue: "Continue with Google",
        emailLink: "Email link",
        authStatus: "Log in to use Premium features.",
        accountTitle: "My page",
        accountNote: "Check your account, plan, and usage.",
        email: "Email",
        currentPlan: "Current plan",
        cloudUsage: "Cloud usage",
        aiUsage: "AI usage",
        premiumUpgrade: "Upgrade to Premium",
        logout: "Log out",
        pricingTitle: "Switch to Lecture Premium",
        pricingBody: "Keep basic accessibility captions free, and test Premium only for class-material generation, caption files, and long-session conversion.",
        freePrice: "$0",
        freeCaption: "Basic accessibility captions",
        freeFeature1: "Local live captions",
        freeFeature2: "TXT download",
        freeFeature3: "3 material generations",
        freeFeature4: "10 cloud minutes",
        premiumPrice: "$9.99/month",
        premiumCaption: "Automated lecture captions and class materials",
        premiumFeature1: "600 high-accuracy cloud minutes without API keys",
        premiumFeature2: "300 class-material/question requests without API keys",
        premiumFeature3: "SRT/VTT/PDF export",
        premiumFeature4: "60 long-recording final conversions",
        startPremium: "Start $9.99/month",
        viewSample: "View sample",
        proPrice: "$19.99+/month",
        proCaption: "Operations for instructors and schools",
        proFeature1: "Higher limits for long classes/sessions",
        proFeature2: "Advanced shared-room features",
        proFeature3: "History search/folders",
        proFeature4: "Education support",
        contactUs: "Contact us",
        limitReached: "Free limit reached",
        upgradeReason: "Continue with Premium.",
        upgradeCloud: "600 high-accuracy cloud minutes",
        upgradeAi: "300 class-material requests",
        upgradeExport: "SRT/VTT/PDF saving",
        viewPremium: "View Premium",
        later: "Later"
    },
    ko: {
        navLive: "실시간 자막",
        navHistory: "지난 자막",
        navGuide: "사용 가이드",
        statusReady: "시스템 준비됨",
        micLevel: "마이크 감도",
        myPage: "마이페이지",
        login: "로그인",
        heroTitle: "강의 실시간 자막 송출",
        heroBody: "강의 중 자막을 화면과 링크로 공유하고, 종료 후 강의노트와 SRT/VTT/PDF를 만듭니다.",
        micLabel: "이용 가능한 마이크",
        micSelect: "이용 가능한 마이크 선택",
        micPermission: "마이크 권한 허용하기",
        modeLabel: "자막 모드 선택 (Mode)",
        localMode: "내 기기에서 처리",
        cloudMode: "클라우드 고정밀",
        settings: "Settings",
        translationLabel: "번역 언어",
        noTranslation: "번역 안 함",
        lessonTitle: "수업명",
        lessonPlaceholder: "예: 중3 과학 2단원",
        lessonNote: "수업명은 지난 자막에 함께 저장됩니다. 화자 구분이나 기관 자체 키는 고급 설정에서 선택할 수 있습니다.",
        premiumExperiment: "강의자료 Premium 실험",
        premiumPreview: "강의 Premium 보기",
        freePreview: "Free로 보기",
        flowLiveTitle: "실시간 자막",
        flowLiveBody: "마이크 소리를 바로 큰 자막으로 보여줍니다.",
        flowShareTitle: "학생 링크 공유",
        flowShareBody: "QR 링크로 학생 화면에 자막을 보냅니다.",
        flowNotesTitle: "강의자료 생성",
        flowNotesBody: "강의노트와 SRT/VTT/PDF로 정리합니다.",
        sampleTitle: "샘플 결과물",
        sampleBody: "강의가 끝나면 자막 원문을 복습자료 형태로 정리합니다.",
        sampleApply: "샘플 적용",
        lectureNote: "강의노트",
        sampleLessonTitle: "중3 과학: 전류와 전압",
        sampleLessonBody: "핵심 개념 3개, 헷갈리는 용어, 복습 질문, 다음 수업 과제를 한 문서로 정리합니다.",
        subtitleFile: "자막 파일",
        subtitleFileBody: "녹화 강의 업로드에 바로 쓰는 시간표시 자막 파일을 만듭니다.",
        cloudHigh: "클라우드 고정밀",
        serverCredit: "LiveNote 서버 크레딧 사용 중 · API 키 설정 없이 사용",
        advancedSettings: "고급 설정",
        closeSettings: "설정 닫기",
        advancedApi: "고급 API 설정",
        useMyApi: "내 API 키 사용",
        provider: "제공업체",
        model: "모델",
        apiKey: "API 키",
        keyStorage: "키 저장 위치",
        saveBrowser: "이 브라우저에 저장",
        saveSession: "이번 세션만 저장",
        extraSettings: "추가 설정",
        extraPlaceholder: "서비스 URL 또는 리전",
        diarization: "화자 분리 사용",
        providerHelp: "Free/Premium은 LiveNote 서버 크레딧으로 바로 사용할 수 있습니다. 개발자나 기관만 자체 API 키를 선택하세요.",
        apiCostNote: "내 API 키를 쓰면 LiveNote 사용량 한도 대신 해당 API 제공업체 비용이 직접 발생합니다. 키는 이 브라우저에만 저장됩니다.",
        groqKeyTest: "Groq 키 테스트 입력",
        makeGroqKey: "Groq API 키 만들기",
        makeOpenAiKey: "OpenAI API 키 만들기",
        joinGladia: "Gladia 가입",
        joinSpeechmatics: "Speechmatics 가입",
        fontSize: "글자 크기 (Size)",
        textColor: "글자 색상 (Color)",
        captionBackground: "자막 배경색 (Background)",
        opacity: "배경 투명도 (Opacity)",
        settingsNote: "변경한 설정은 실시간 자막, 공유 보기, PIP 모드에 즉시 반영되고 이 브라우저에 저장됩니다.",
        livePanel: "실시간 자막",
        reset: "초기화",
        largeCaption: "큰 자막",
        defaultView: "기본 화면",
        pipMode: "PIP 모드",
        classMaterials: "강의자료",
        materialSettings: "자료 설정",
        advancedAiApi: "강의자료 고급 API 설정",
        aiEmpty: "강의가 끝나면 핵심 요약, 복습 포인트, 과제 힌트를 자료로 정리합니다.",
        questionPlaceholder: "자막 내용에 대해 질문하세요",
        send: "전송",
        meetingMinutes: "회의록",
        lectureNotes: "강의 노트",
        consultingRecord: "상담 기록",
        createMaterials: "자료 만들기",
        copyMarkdown: "Markdown 복사",
        downloadMd: "MD 다운로드",
        startCaptions: "자막 시작",
        endSession: "세션 종료",
        summarize: "핵심 정리",
        downloadTxt: "TXT 다운로드",
        downloadRecording: "녹음 다운로드",
        finalTranscribe: "최종 변환",
        shareStudentLink: "학생 링크 공유",
        debugReady: "시스템 준비 완료.",
        sharedBeta: "공유 보기 베타",
        backToLive: "실시간 자막으로 돌아가기",
        roomId: "방 번호 (Room ID)",
        roomPlaceholder: "방 번호를 입력하거나 생성하세요",
        generateId: "ID 생성",
        currentStatus: "현재 상태",
        waiting: "연결 대기 중...",
        role: "역할 선택",
        senderRole: "보내기 (휴대폰용)",
        receiverRole: "받아보기 (PC/태블릿용)",
        sharePlaceholder: "방 번호를 만들면 공유 링크가 생성됩니다.",
        copyLink: "링크 복사",
        stageLink: "송출 링크",
        makeQr: "QR 만들기",
        audienceNote: "청중은 링크나 QR로 바로 받아보기 모드에 들어올 수 있습니다. 송출 모드는 프로젝터/큰 화면용입니다.",
        sharedView: "공유 보기",
        stageMode: "송출 모드",
        stageEnd: "송출 종료",
        clearScreen: "화면 비우기",
        connect: "연결하기",
        disconnect: "연결 해제",
        savedHistory: "저장된 자막 기록",
        deleteAll: "전체 삭제",
        privacy: "개인정보처리방침",
        terms: "이용약관",
        contact: "문의하기",
        authTitle: "Premium 로그인",
        authNote: "Premium 기능을 계정에 연결하려면 먼저 로그인하세요.",
        close: "닫기",
        googleContinue: "Google로 계속",
        emailLink: "이메일 링크",
        authStatus: "Premium 기능을 사용하려면 로그인하세요.",
        accountTitle: "마이페이지",
        accountNote: "계정, 플랜, 사용량을 확인합니다.",
        email: "이메일",
        currentPlan: "현재 플랜",
        cloudUsage: "클라우드 사용량",
        aiUsage: "AI 사용량",
        premiumUpgrade: "Premium 업그레이드",
        logout: "로그아웃",
        pricingTitle: "강의용 Premium으로 전환",
        pricingBody: "기본 접근성 자막은 무료로 유지하고, 강의자료 생성·자막 파일·장시간 변환만 Premium으로 실험합니다.",
        freePrice: "0원",
        freeCaption: "기본 접근성 자막",
        freeFeature1: "로컬 실시간 자막",
        freeFeature2: "TXT 다운로드",
        freeFeature3: "자료 정리 3회",
        freeFeature4: "클라우드 10분",
        premiumPrice: "월 9,900원",
        premiumCaption: "강의 자막과 수업자료 자동화",
        premiumFeature1: "API 키 없이 클라우드 고정밀 600분",
        premiumFeature2: "API 키 없이 강의자료/질문 300회",
        premiumFeature3: "SRT/VTT/PDF 내보내기",
        premiumFeature4: "긴 녹음 최종 변환 60회",
        startPremium: "월 9,900원 시작",
        viewSample: "샘플 보기",
        proPrice: "월 19,900원~",
        proCaption: "강사·교육기관용 운영 기능",
        proFeature1: "긴 강의/세션 한도 확대",
        proFeature2: "공유 방 고급 기능",
        proFeature3: "기록 검색/폴더",
        proFeature4: "교육기관 문의 대응",
        contactUs: "문의하기",
        limitReached: "무료 한도에 도달했습니다",
        upgradeReason: "Premium으로 계속 사용할 수 있습니다.",
        upgradeCloud: "고정밀 클라우드 600분",
        upgradeAi: "강의자료 300회",
        upgradeExport: "SRT/VTT/PDF 저장",
        viewPremium: "Premium 보기",
        later: "나중에"
    }
};

const UI_TEXT_KEYS = Object.keys(UI_TEXT.en);
const UI_TEXT_LOOKUP = UI_TEXT_KEYS.reduce((map, key) => {
    map[UI_TEXT.en[key]] = key;
    map[UI_TEXT.ko[key]] = key;
    return map;
}, {});

const STT_PROVIDER_MODELS = {
    groq: [
        { value: "whisper-large-v3", label: "whisper-large-v3" },
        { value: "whisper-large-v3-turbo", label: "whisper-large-v3-turbo" }
    ],
    openai: [
        { value: "gpt-4o-mini-transcribe", label: "gpt-4o-mini-transcribe" },
        { value: "gpt-4o-transcribe", label: "gpt-4o-transcribe" },
        { value: "whisper-1", label: "whisper-1" }
    ],
    gladia: [{ value: "standard", label: "Gladia standard" }],
    speechmatics: [
        { value: "enhanced", label: "Enhanced" },
        { value: "standard", label: "Standard" }
    ],
    ibm: [
        { value: "ko-KR_BroadbandModel", label: "한국어 Broadband" },
        { value: "en-US_BroadbandModel", label: "English US Broadband" }
    ],
    azure: [{ value: "conversation", label: "Conversation" }]
};

const STT_PROVIDER_META = {
    groq:         { summary: "개인 GROQ API 사용 중",         help: "Groq 키 하나로 Whisper 기반 고정밀 자막을 사용할 수 있습니다.", extra: "" },
    openai:       { summary: "개인 OPENAI API 사용 중",       help: "OpenAI 키 하나로 고정밀 자막을 사용할 수 있습니다.", extra: "" },
    gladia:       { summary: "개인 GLADIA API 사용 중",       help: "Gladia는 무료 제공량이 넉넉한 편이라 긴 사용에 적합합니다.", extra: "" },
    speechmatics: { summary: "개인 SPEECHMATICS API 사용 중", help: "Speechmatics는 악센트와 다양한 발화에 강한 편입니다.", extra: "" },
    ibm:          { summary: "개인 IBM WATSON API 사용 중",   help: "IBM Watson은 API 키와 서비스 URL이 모두 필요합니다.", extra: { label: "서비스 URL", placeholder: "https://api.<region>.speech-to-text.watson.cloud.ibm.com" } },
    azure:        { summary: "개인 AZURE SPEECH API 사용 중", help: "Azure Speech는 API 키와 리전이 필요합니다.", extra: { label: "리전", placeholder: "koreacentral, eastus 등" } }
};

const AI_PROVIDER_MODELS = {
    gemini: [
        { value: "gemini-1.5-flash", label: "gemini-1.5-flash" },
        { value: "gemini-1.5-pro", label: "gemini-1.5-pro" }
    ],
    openai: [
        { value: "gpt-4o-mini", label: "gpt-4o-mini" },
        { value: "gpt-4o", label: "gpt-4o" },
        { value: "gpt-4.1-mini", label: "gpt-4.1-mini" }
    ],
    groq: [
        { value: "llama-3.1-8b-instant", label: "llama-3.1-8b-instant" },
        { value: "llama-3.3-70b-versatile", label: "llama-3.3-70b-versatile" }
    ]
};